name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day. https://crontab.guru/
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in latest medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:      
          feed_list: "https://milanpanchal24.medium.com/feed" # Replace this URL with your rss feed URLs separated by comma
